version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "derTobsch"
    default_labels:
      - "dependencies"
      - "dependabot"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
