name: Urlaubsverwaltung CI

on:
  schedule:
    - cron: "2 4 * * *"
  push:
    branches:
      - master
      - v3.x
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build and analyse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache pom dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            node/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: ./mvnw --batch-mode -Pcoverage clean verify
      - name: Assets-Manifest commit
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.name "Tobias Schneider[bot]"
          git config --local user.email schneider@synyx.de
          git diff --quiet --name-only src/main/webapp/WEB-INF/assets-manifest.json || (git add src/main/webapp/WEB-INF/assets-manifest.json; git commit -m  "Adapt assets-manifest")
      - name: Assets-Manifest push
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}
          repository: synyx/urlaubsverwaltung
      - name: Analyse with SonarCloud
        run: >
          ./mvnw --batch-mode
          -Pcoverage
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=synyx
          -Dsonar.projectKey=org.synyx:urlaubsverwaltung
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml
          -Dsonar.javascript.lcov.reportPaths=target/js-coverage/lcov.info
          -Dsonar.javascript.exclusions=**/__tests__/**,**/*-spec.js,**/*.spec.js,**/*-test.js,**/*.test.js
          -Dsonar.eslint.reportPaths=target/js-eslint/report.json
          -Dsonar.coverage.exclusions=**/__tests__/**,**/*-spec.js,**/*.spec.js,**/*-test.js,**/*.test.js
          -Dsonar.sources=src/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build docker image and push to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        run: >
          ./mvnw --batch-mode
          docker:build
          docker:push
          -Ddocker.name=synyx/urlaubsverwaltung
          -Ddocker.push.registry=ghcr.io
          -Ddocker.push.username=${{ github.actor }}
          -Ddocker.push.password=${{ secrets.CR_PAT }}
          -Ddocker.pull.username=${{ secrets.DOCKER_USERNAME }}
          -Ddocker.pull.password=${{ secrets.DOCKER_PASSWORD }}
