name: Urlaubsverwaltung Release Trigger

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'x.xx.x'
      nextVersion:
        description: 'Next version'
        required: true
        default: 'x.xx.x-SNAPSHOT'

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache pom dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            node/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Trigger Release
        run: ./release.sh
        env:
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
          NEW_VERSION: ${{ github.event.inputs.nextVersion }}
